CREATE ROLES ROLE_SU;
GRANT SELECT, INSERT, UPDATE, DELETE ON SYS.USERS TO ROLE_SU;
GRANT SELECT, INSERT, UPDATE, DELETE ON SYS.USER_PHONE TO ROLE_SU;
GRANT SELECT, INSERT, UPDATE, DELETE ON SYS.LOGIN TO ROLE_SU;
GRANT SELECT, INSERT, UPDATE, DELETE ON SYS.PROPERTY TO ROLE_SU;
GRANT SELECT, INSERT, UPDATE, DELETE ON SYS.PROP_OWNED TO ROLE_SU;
GRANT SELECT, INSERT, UPDATE, DELETE ON SYS.PROP_RENTED TO ROLE_SU;


CREATE ROLES ROLE_M;
GRANT SELECT, UPDATE ON SYS.USERS TO ROLE_M;
GRANT SELECT, UPDATE ON SYS.USER_PHONE TO ROLE_M;
GRANT SELECT, UPDATE ON SYS.LOGIN TO ROLE_M;
GRANT SELECT, INSERT, UPDATE, DELETE ON SYS.PROPERTY TO ROLE_M;
GRANT SELECT, INSERT, UPDATE, DELETE ON SYS.PROP_OWNED TO ROLE_M;
GRANT SELECT, INSERT, UPDATE, DELETE ON SYS.PROP_RENTED TO ROLE_M;


CREATE ROLES ROLE_O;
GRANT SELECT, UPDATE ON SYS.USERS TO ROLE_O;
GRANT SELECT, DELETE, INSERT, UPDATE ON SYS.USER_PHONE TO ROLE_O;
GRANT SELECT, UPDATE ON SYS.LOGIN TO ROLE_O;
GRANT SELECT, INSERT, UPDATE, DELETE ON SYS.PROPERTY TO ROLE_O;
GRANT SELECT, INSERT, UPDATE, DELETE ON SYS.PROP_OWNED TO ROLE_O;
GRANT SELECT, INSERT, UPDATE, DELETE ON SYS.PROP_RENTED TO ROLE_O;


CREATE ROLES ROLE_T;
GRANT SELECT, UPDATE ON SYS.USERS TO ROLE_T;
GRANT SELECT, INSERT, UPDATE, DELETE ON SYS.USER_PHONE TO ROLE_T;
GRANT SELECT, UPDATE ON SYS.LOGIN TO ROLE_T;
GRANT SELECT, INSERT ON SYS.PROPERTY TO ROLE_T;
GRANT SELECT, INSERT ON SYS.PROP_OWNED TO ROLE_T;
GRANT SELECT, INSERT, UPDATE, DELETE ON SYS.PROP_RENTED TO ROLE_T;

